# Generated by Django 5.0 on 2024-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_registration',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
