# Generated by Django 5.0 on 2024-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0002_alter_emp_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
