# Generated by Django 5.0 on 2024-01-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_registration.position')),
            ],
        ),
        migrations.DeleteModel(
            name='Emp_Registration',
        ),
    ]
