# Generated by Django 5.0 on 2024-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0004_empregistration_delete_emp_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
