# Generated by Django 5.0 on 2024-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0007_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoopingCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=100)),
                ('door_number', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('conutry', models.CharField(max_length=100)),
            ],
        ),
    ]
